### DISCUSSION TITLE
How to change payload size 100MB on Application Load balancing AWS

### DISCUSSION THREAD

**Discussion by Kamlesh-at-bit** [aws/aws-sdk-js#4571] [Q&A]
**I did these changes on main.ts**

```
app.use(bodyParser.json({ limit: "150mb" }));
app.use(bodyParser.urlencoded({ limit: "150mb", extended: true }));
app.use(bodyParser.text({ limit: "150mb" }));
```

**and my ingress.yaml file looks like**

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: core-api
  namespace: {{.Values.namespace }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: {{.Values.ingress.certificate}}
spec:
  ingressClassName: alb
  tls:
    - hosts:
        - {{.Values.ingress.host}}
```

Steps for changes on AWS server using CLI and AWS Management Console.

Thanks,
