### ISSUE TITLE
Typescript definition for AttributeValue for DynamoDb leads to query failures

### ISSUE THREAD

**Issue by schatekar** [aws/aws-sdk-js#1736]
I have a DynamoDb table named `User` which has a key schema like the below

```yaml
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "Users"
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
```

I am using the following typescript code to query from this table

```js
let params: QueryInput = {
      TableName: "Users",
      KeyConditionExpression: "#id = :id",
      ExpressionAttributeNames: {
        "#id": "id"
      },
      ExpressionAttributeValues: {
        ":id": {
              S: "1"
           }
      }
    }

    let result = await ddbClient.query(params).promise();
```
This is resulting in the following error

```shell
ValidationException: One or more parameter values were invalid: Condition parameter type does not match schema type
```
I have read on the internet that you do not need to specify the types in `ExpressionAttributeValue`. However, due to the published definition of `AttributeValue` interface, I cannot do away without specifying the type. What I am doing, for now, is declaring the `params` variable to be of type `any` and get rid of type specified in the `ExpressionAttributeValue` like the below

```js
let params: any = {
      TableName: "Users",
      KeyConditionExpression: "#id = :id",
      ExpressionAttributeNames: {
        "#id": "id"
      },
      ExpressionAttributeValues: {
        ":id": "1"
      }
    }

    let result = await ddbClient.query(params).promise();

```

This works. Is this a bug? Or am I doing something wrong?
