### ISSUE TITLE
S3 getSignedUrl doesn't work with TemporaryCredentials

### ISSUE THREAD

**Issue by ttulka** [aws/aws-sdk-js#2109]
I have a role `arn:aws:iam::1234567890:role/my-role`:
```
  MyRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "my-role"
      Path: /
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            AWS: "*"
          Action: sts:AssumeRole
        - Effect: Allow
          Principal:
            Service: [lambda.amazonaws.com]
          Action: sts:AssumeRole
        - Effect: Allow
          Principal:
            Service: [s3.amazonaws.com]
          Action: sts:AssumeRole
      Policies:
      - PolicyName: my-role-policy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Action: ["s3:*"]
            Resource: !Sub "arn:aws:s3:::*/XXX/*"
            Effect: Allow
```
I want to assume the role in my service to assure the user gets only access to his resources (with a sub-key `/XXX/`).

I create a S3 client with a temporary credentials based on this role:
```
const tempCreds = new AWS.TemporaryCredentials({
  RoleArn: 'arn:aws:iam::1234567890:role/my-role'
});
const s3 = new AWS.S3({credentials: tempCreds, apiVersion: '2006-03-01', signatureVersion: 'v4'});
```

Getting an object works fine:
```
s3.getObject({Bucket: 'mybucket', Key: '0790c020/XXX/abc.jpg'}, function(err, data) {
    if (err) console.log(err, err.stack);
    else console.log(data);
})
```

But by retrieiving a signed URL:
```
console.log(s3.getSignedUrl('putObject', {Bucket: 'mybucket', Key: '0790c020/XXX/abc.jpg'}))
```
I got always this:
```
https://s3.eu-central-1.amazonaws.com/
```
No error occurs.

Without the credentials parameter:
```
const s3 = new AWS.S3({/*credentials: tempCreds,*/ apiVersion: '2006-03-01', signatureVersion: 'v4'});
```
it works as expected:
```
https://mybucket.s3.eu-central-1.amazonaws.com/0790c020/XXX/abc.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAAAAAAAAAA%2F20180626%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20180626T123119Z&X-Amz-Expires=900&X-Amz-Signature=00000000000000000&X-Amz-SignedHeaders=host
```
