### ISSUE TITLE
AWS.DynamoDB.DocumentClient & AWS.DynamoDB same scan diff results

### ISSUE THREAD

**Issue by tzookb** [aws/aws-sdk-js#2132]
I run this simple scan:

```
{
        TableName: USERS_TABLE,
        ExpressionAttributeValues: { 
            ':value': {S: email}
        },
        FilterExpression: 'email = :value',
    }
```

in `AWS.DynamoDB.DocumentClient` I get not result

but in `AWS.DynamoDB` I get the needed result

this is  the table definition in yaml:
```
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: email
            KeyType: RANGE
        GlobalSecondaryIndexes:
        - IndexName: emailIndex
          KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: email
            KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
```
