### ISSUE TITLE
No answer from CognitoIdentityServiceProvider.ListUser or GetUser

### ISSUE THREAD

**Issue by namelesswc** [aws/aws-sdk-js#2631]
I'm trying to get the username in a aws-lambda function. I can get userPoolId, userPoolUserId, cognitoIdentityId from event. However I don't get an answer when calling CognitoIdentityServiceProvider.ListUser or GetUser. My request finishes and returns a 200 to my client. Policies should be correct. I also tried to use the callback instead of promise. Same result.

"aws-sdk": "^2.409.0",

Log on cloud watch:
userSub: ***** (correct)
userPoolId: **** (correct)
got user: undefined

```javascript
export async function main(event) {
  const data = JSON.parse(event.body);

  const authProvider = event.requestContext.identity.cognitoAuthenticationProvider;
  const parts = authProvider.split(":");
  const userPoolIdParts = parts[parts.length - 3].split("/");

  const userPoolId = userPoolIdParts[userPoolIdParts.length - 1];
  const userPoolUserId = parts[parts.length - 1];

  var cog = new AWS.CognitoIdentityServiceProvider();

  let sub = event.requestContext.identity.cognitoAuthenticationProvider.split(
    ":CognitoSignIn:"
  )[1];
  console.log("userSub:  " + sub);
  console.log("userPoolId: " + userPoolId);
  let request = {
    UserPoolId: userPoolId,
    Filter: null,
    Limit: 10
  };
  let users = await cog.listUsers(request).promise();
  console.log("got user:", users[0]);

  const params = {
    TableName: "*********",
    Item: {
      //Replace id with username
      cognitoIdentityId: event.requestContext.identity.cognitoIdentityId,
      content: data.content,
      createdAt: Date.now()
    }
  };

  try {
    await dynamoDbLib.call("put", params);
    return success(params.Item);
  } catch (e) {
    console.log(e);
    return failure(params.Item);
  }
}
```

```yaml
- Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:us-east-1:870567203339:table/******"
        - "arn:aws:dynamodb:us-east-1:870567203339:table/***"
    - Effect: Allow
      Action:
        - cognito-identity:Describe*
        - cognito-identity:Get*
        - cognito-identity:List*
        - cognito-idp:Describe*
        - cognito-idp:AdminGetUser
        - cognito-idp:AdminList*
        - cognito-idp:List*
        - cognito-sync:Describe*
        - cognito-sync:Get*
        - cognito-sync:List*
        - iam:ListOpenIdConnectProviders
        - iam:ListRoles
        - sns:ListPlatformApplications
      Resource:
        - "arn:aws:cognito-idp:us-east-1:*******:userpool/us-east-1_******"

functions:
  put-profile:
    handler: api/put-profile.main
    events:
      - http:
          path: users/{id}
          method: put
          cors: true
          authorizer: aws_iam
```
